name: block_demo_dharmesh
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  rx_bloc_cli: ^3.4.1
  connectivity_plus: ^6.0.3 # Internet Connection

  intl: ^0.18.1
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  fpdart: ^1.1.0
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^1.1.3
  internet_connection_checker: ^1.0.0+1

  shared_preferences: ^2.0.15
  image_picker: ^1.0.8
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
  lottie: ^2.3.2
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_staggered_animations: ^1.1.1

  open_filex: ^4.4.0 # Opens Files
  file_picker: ^8.0.3 # Picks Files From Documents and Downloads

  get_it: ^7.2.0
  
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.2
  introduction_screen: ^3.0.2


dependency_overrides:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/illustrations/
    - assets/icons/logo/
    - assets/icons/general/home/
    - assets/icons/general/social/
    - assets/icons/general/bottom_nav/
    - assets/images/
    - assets/animation/
